// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwPb-Ir2jcnuZADlg8YKXYwuT1o3_s-xE',
    appId: '1:244235600424:web:b78c70a4ce3c3efefa2b1d',
    messagingSenderId: '244235600424',
    projectId: 'well-organized-1ab1d',
    authDomain: 'well-organized-1ab1d.firebaseapp.com',
    databaseURL: 'https://well-organized-1ab1d-default-rtdb.firebaseio.com',
    storageBucket: 'well-organized-1ab1d.appspot.com',
    measurementId: 'G-CC5ME7T461',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOU0zUo9PIog1cEo1oSSiRZ6WG6Y4y3Hk',
    appId: '1:244235600424:android:31cf755be8acd0b4fa2b1d',
    messagingSenderId: '244235600424',
    projectId: 'well-organized-1ab1d',
    databaseURL: 'https://well-organized-1ab1d-default-rtdb.firebaseio.com',
    storageBucket: 'well-organized-1ab1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLHElOUZIt9ecTtGjuTCKiVcskJflxOKM',
    appId: '1:244235600424:ios:1a905b4c19f83a5dfa2b1d',
    messagingSenderId: '244235600424',
    projectId: 'well-organized-1ab1d',
    databaseURL: 'https://well-organized-1ab1d-default-rtdb.firebaseio.com',
    storageBucket: 'well-organized-1ab1d.appspot.com',
    iosClientId: '244235600424-8jujm3p9l6qla9dq4d6d3vlsupuot174.apps.googleusercontent.com',
    iosBundleId: 'com.example.wellOrganized',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLHElOUZIt9ecTtGjuTCKiVcskJflxOKM',
    appId: '1:244235600424:ios:1a905b4c19f83a5dfa2b1d',
    messagingSenderId: '244235600424',
    projectId: 'well-organized-1ab1d',
    databaseURL: 'https://well-organized-1ab1d-default-rtdb.firebaseio.com',
    storageBucket: 'well-organized-1ab1d.appspot.com',
    iosClientId: '244235600424-8jujm3p9l6qla9dq4d6d3vlsupuot174.apps.googleusercontent.com',
    iosBundleId: 'com.example.wellOrganized',
  );
}
